export enum TaskStatus {
  COMPLETED = 'COMPLETED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  BLOCKER = 'BLOCKER'
}

export enum TaskType {
  RECRUITMENT = 'RECRUITMENT',
  OPERATION = 'OPERATION',
  CULTURAL = 'CULTURAL',
  APPRECIATION = 'APPRECIATION',
  ADMIN = 'ADMIN',
}
